### ISSUE TITLE
No Network Appearing in Dropdown

### ISSUE THREAD

**Issue by SpaceCadetUWG** [googleads/dfp-playground#5]
I used to be able to select any of my networks in the dropdown in the test app and be able to pull data in through it. Is there any reason that suddenly I can't see my networks in the test app? Is it because of the name and URL changes?

**Comment by kelvin-chappell** [comment]
This seems to be because the version of the API that the app uses has been deprecated.
This can be seen in the ajax call to `https://dfp-playground.appspot.com/api/networks`, which gives an error (HTTP 500) response:
```
Version v201708 was deprecated and is now disabled. Please check the DoubleClick for Publishers blog for more information or contact us via the support forum.
```

PS:
Just noticed this has already been noted in https://github.com/googleads/dfp-playground/issues/4

**Comment by ffeast** [comment]
Same problem

**Comment by donovanfm** [comment]
The issue has now been fixed.

**Comment by spirestar22** [comment]
How may I update the api?

**Comment by kelvin-chappell** [comment]
@spirestar22 Update the dependency [here](https://github.com/googleads/dfp-playground/blob/master/requirements.txt#L2). See [this commit](https://github.com/googleads/dfp-playground/commit/4fdbc922798a88cd80eeb14140385e5d47117f89) for an example.
